// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: lopezator/filterer/v1/filterer.proto

package filterer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the table and the filter string.
type FilterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Table  string `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	Filter string `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
}

func (x *FilterRequest) Reset() {
	*x = FilterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lopezator_filterer_v1_filterer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FilterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterRequest) ProtoMessage() {}

func (x *FilterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lopezator_filterer_v1_filterer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterRequest.ProtoReflect.Descriptor instead.
func (*FilterRequest) Descriptor() ([]byte, []int) {
	return file_lopezator_filterer_v1_filterer_proto_rawDescGZIP(), []int{0}
}

func (x *FilterRequest) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *FilterRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

// The response message containing the sql to issue the filtering, based on the filter request.
type FilterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sql string `protobuf:"bytes,1,opt,name=sql,proto3" json:"sql,omitempty"`
}

func (x *FilterResponse) Reset() {
	*x = FilterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lopezator_filterer_v1_filterer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FilterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterResponse) ProtoMessage() {}

func (x *FilterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lopezator_filterer_v1_filterer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterResponse.ProtoReflect.Descriptor instead.
func (*FilterResponse) Descriptor() ([]byte, []int) {
	return file_lopezator_filterer_v1_filterer_proto_rawDescGZIP(), []int{1}
}

func (x *FilterResponse) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

var File_lopezator_filterer_v1_filterer_proto protoreflect.FileDescriptor

var file_lopezator_filterer_v1_filterer_proto_rawDesc = []byte{
	0x0a, 0x24, 0x6c, 0x6f, 0x70, 0x65, 0x7a, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x66, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x2f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x65, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x6c, 0x6f, 0x70, 0x65, 0x7a, 0x61, 0x74, 0x6f,
	0x72, 0x2e, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x22, 0x3d, 0x0a,
	0x0d, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x61, 0x62, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x22, 0x22, 0x0a, 0x0e,
	0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x73, 0x71, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x71, 0x6c,
	0x32, 0x6a, 0x0a, 0x0f, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x57, 0x0a, 0x06, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x24, 0x2e,
	0x6c, 0x6f, 0x70, 0x65, 0x7a, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x6c, 0x6f, 0x70, 0x65, 0x7a, 0x61, 0x74, 0x6f, 0x72, 0x2e,
	0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x37, 0x5a, 0x35,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x6f, 0x70, 0x65, 0x7a,
	0x61, 0x74, 0x6f, 0x72, 0x2f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x65, 0x72, 0x2d, 0x67, 0x6f,
	0x2f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x3b, 0x66, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_lopezator_filterer_v1_filterer_proto_rawDescOnce sync.Once
	file_lopezator_filterer_v1_filterer_proto_rawDescData = file_lopezator_filterer_v1_filterer_proto_rawDesc
)

func file_lopezator_filterer_v1_filterer_proto_rawDescGZIP() []byte {
	file_lopezator_filterer_v1_filterer_proto_rawDescOnce.Do(func() {
		file_lopezator_filterer_v1_filterer_proto_rawDescData = protoimpl.X.CompressGZIP(file_lopezator_filterer_v1_filterer_proto_rawDescData)
	})
	return file_lopezator_filterer_v1_filterer_proto_rawDescData
}

var file_lopezator_filterer_v1_filterer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_lopezator_filterer_v1_filterer_proto_goTypes = []interface{}{
	(*FilterRequest)(nil),  // 0: lopezator.filterer.v1.FilterRequest
	(*FilterResponse)(nil), // 1: lopezator.filterer.v1.FilterResponse
}
var file_lopezator_filterer_v1_filterer_proto_depIdxs = []int32{
	0, // 0: lopezator.filterer.v1.FiltererService.Filter:input_type -> lopezator.filterer.v1.FilterRequest
	1, // 1: lopezator.filterer.v1.FiltererService.Filter:output_type -> lopezator.filterer.v1.FilterResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_lopezator_filterer_v1_filterer_proto_init() }
func file_lopezator_filterer_v1_filterer_proto_init() {
	if File_lopezator_filterer_v1_filterer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_lopezator_filterer_v1_filterer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FilterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lopezator_filterer_v1_filterer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FilterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lopezator_filterer_v1_filterer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lopezator_filterer_v1_filterer_proto_goTypes,
		DependencyIndexes: file_lopezator_filterer_v1_filterer_proto_depIdxs,
		MessageInfos:      file_lopezator_filterer_v1_filterer_proto_msgTypes,
	}.Build()
	File_lopezator_filterer_v1_filterer_proto = out.File
	file_lopezator_filterer_v1_filterer_proto_rawDesc = nil
	file_lopezator_filterer_v1_filterer_proto_goTypes = nil
	file_lopezator_filterer_v1_filterer_proto_depIdxs = nil
}
