name: buf-pull-request
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check out the code.
      - uses: actions/checkout@v4
      # Set up the buf CLI.
      - uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ github.token }}
      # Check that the protobuf files are well-formed.
      - uses: bufbuild/buf-lint-action@v1
        with:
          input: "proto"
      # Check that the protobuf files are formatted.
      - run: buf format proto --exit-code
      # Check that we are not breaking backwards compatibility.
      - uses: bufbuild/buf-breaking-action@v1
        with:
          input: "proto"
          # The 'main' branch of the GitHub repository that defines the module.
          against: "https://github.com/${GITHUB_REPOSITORY}.git#branch=main"
